services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecommerce_db'
      - 'POSTGRES_PASSWORD=ecommerce_user'
      - 'POSTGRES_USER=ecommerce_pass'
    ports:
      - '5432'
